django_esp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include("prueba.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

prueba/urls.py
from django.urls import path
from prueba import views


app_name = 'luces_app'

urlpatterns = [
    path("list/",views.ListPruebaAPIView.as_view(),name="prueba_list"),
    path("estado/<int:pk>/",views.EstadoAPIView.as_view(),name="estado"),
    path("create/", views.CreatePruebaAPIView.as_view(),name="prueba_create"),
    path("update/<int:pk>/",views.UpdatePruebaAPIView.as_view(),name="update_prueba"),
    path("delete/<int:pk>/",views.DeletePruebaAPIView.as_view(),name="delete_prueba"),
    path("luces2/",views.LucesListView2.as_view(),name="Luces2"),
    path("editar/<int:pk>/",views.FormularioListView.as_view(),name="editar"),
    path("formulario2/",views.FormularioListView2.as_view(),name="formulario2"),
    path("luces/",views.LucesListView3.as_view(),name="Luces"),
    path("list2/",views.ListPruebaAPIView2.as_view(),name="prueba_list2"),
    path("panel/",views.PanelView.as_view(),name="panel"),
    ##Aca van las vistas del logger.
    path("logger/",views.ListLoggerAPIView.as_view(),name="logger"),
    path("logger/create/",views.CreateLoggerAPIView.as_view(),name="logger_create"),

]

prueba/models.py
from django.db import models

# Create your models here.


class Prueba(models.Model):
    Luz = models.IntegerField(primary_key=True)
    encendido = models.BooleanField(default=False)
    Ip = models.GenericIPAddressField(protocol='IPv4',default='0.0.0.0')
    descripcion = models.CharField(max_length=100,default='A determinar')
    def __str___(self):
        return self.title


class Logger(models.Model):
    luz = models.CharField(max_length=20,default='0')
    df = models.CharField(max_length=20,default='0')
    ram = models.CharField(max_length=20,default='0')
    wifi_ip = models.CharField(max_length=20,default='0')
    created_on = models.DateTimeField(auto_now_add=True)

prueba/views.py
import os
import psutil
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from django.shortcuts import get_object_or_404
from rest_framework.generics import ListAPIView, CreateAPIView, DestroyAPIView, UpdateAPIView
from prueba.serializers import PruebaSerializer, ActualizarSerializer,LoggerSerializer,LoggerSerializerComplete
from prueba.models import Prueba, Logger
from rest_framework.response import Response
from django.views.generic import ListView, TemplateView
from rest_framework.renderers import TemplateHTMLRenderer
from django.urls import reverse_lazy, reverse
from django.db.models import Max
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from braces.views import LoginRequiredMixin, CsrfExemptMixin

class ListPruebaAPIView(ListAPIView):
    """This endpoint list all of the available todos from the database"""
    queryset = Prueba.objects.all()
    serializer_class = PruebaSerializer


class EstadoAPIView(ListAPIView):
    """This endpoint list all of the available todos from the database"""
    serializer_class = ActualizarSerializer
    
    def get_queryset(self):
        luz = self.kwargs['pk']
        queryset = Prueba.objects.filter(Luz__icontains=luz)
        return queryset

class CreatePruebaAPIView(CreateAPIView):
    """This endpoint allows for creation of a todo"""
    queryset = Prueba.objects.all()
    serializer_class = PruebaSerializer

class UpdatePruebaAPIView(UpdateAPIView):
    """This endpoint allows for updating a specific todo by passing in the id of the todo to update"""
   
    queryset = Prueba.objects.all()
    serializer_class = ActualizarSerializer


class DeletePruebaAPIView(DestroyAPIView):
    """This endpoint allows for deletion of a specific Todo from the database"""
    queryset = Prueba.objects.all()
    serializer_class = PruebaSerializer

#formulario para crear nuevas luces.

class FormularioListView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'editar.html'
    
    def get(self, request,pk):
        luz = get_object_or_404(Prueba, pk=pk)
        serializer = PruebaSerializer(luz)
        return Response({'serializer': serializer, 'luz': luz})
    
    def post(self, request, pk):
        luz = get_object_or_404(Prueba, pk=pk)
        serializer = PruebaSerializer(luz, data=request.data)
        if not serializer.is_valid():
            return Response({'serializer': serializer, 'luz': luz})
        serializer.save()
        print(reverse_lazy('luces_app:Luces'))
        return redirect(reverse_lazy('luces_app:Luces'))

#Puedo modificar, pero no agregar uno nuevo por lo que me es imprescindible
#crear un formulario que tome el valor mas alto, sume 1 y cree una nueva entrada

class FormularioListView2(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'cargarnuevo.html'
    
    def get(self, request):
        #busco el sk mas alto
        max = Prueba.objects.aggregate(Max('Luz'))['Luz__max']
        #puleo el objeto con el sk mas alto
        luz = get_object_or_404(Prueba, pk=max)
        #lo serializo.
        serializer = PruebaSerializer(luz)
        #Le agrego una unidad mas
        luz.Luz = max + 1
        #muestro el formulario
        return Response({'serializer': serializer,'luz': luz})

    def post(self, request):
        #devuelta 
        max = Prueba.objects.aggregate(Max('Luz'))['Luz__max']
        luz = get_object_or_404(Prueba, pk=max)
        serializer = PruebaSerializer(luz,data=request.data)
        print(serializer)
        luz.Luz = max + 1
        if not serializer.is_valid():
            return Response({'serializer': serializer, 'luz': luz})
        serializer.save()
        return redirect(reverse_lazy('luces_app:Luces'))

#vieja pagina de encendido y apagado
class LucesListView2(ListView):
    model = Prueba
    template_name = "luces2.html"
    context_object_name = 'luz'

#vista que renderiza la pagina con js.
class LucesListView3(LoginRequiredMixin,ListView):
    model = Prueba
    template_name = "luces3.html"
    context_object_name = 'luz'
    
#esta es a la que llama cuando ya esta renderizada la anterior y la usa js para ver el cada luz. 
class ListPruebaAPIView2(LoginRequiredMixin,ListAPIView):
    """This endpoint list all of the available todos from the database"""
    serializer_class = PruebaSerializer
    def get_queryset(self):
        encendido = self.request.query_params.get('encendido',None)
        id =  self.request.query_params.get('id',None)
        
        if(encendido == ""):
            print(encendido)
            return Prueba.objects.all()
        elif(id):
            if (id == '0'):  
                return Prueba.objects.all()
            else:
                return Prueba.objects.filter(Luz = id)          
        else:
            print("entro al else")
            return Prueba.objects.filter(encendido = encendido)
        


class PanelView(TemplateView):
    template_name = "panel.html"
    
    #para pasar un contexto o sea datos a la pagina debemos agregar esto. 
    def datos():
        cpu = {}
        load1, load5, load15 = psutil.getloadavg()
        cpu['load15'] = (load15/os.cpu_count()) * 100
        load15, load30, load60 = psutil.getloadavg()
        cpu['load60'] = (load15/os.cpu_count()) * 100
        cpu['freq'] = psutil.cpu_freq()[0]
        cpu['ram'] =  psutil.virtual_memory()[2]


        return cpu
        

    
    def get_context_data(self, *args, **kwargs):
        context = super(PanelView, self).get_context_data(*args, **kwargs)
        context['name'] = 'Gryffindor'
        context['cpu']  = PanelView.datos
        return context


#################################################################
#Esta vista me permitira guardar la info de loggien de cada luz.
####################################################################


class CreateLoggerAPIView(CreateAPIView):
    """This endpoint allows for creation of a todo"""
    queryset = Logger.objects.all()
    serializer_class = LoggerSerializer

class ListLoggerAPIView(ListAPIView):
    """This endpoint list all of the available todos from the database"""
    queryset = Logger.objects.all().order_by('-id')
    serializer_class = LoggerSerializerComplete

templates/cargarnuevo.html
{% extends 'include/base.html' %}

{% block title %}
Listado de luces

{% endblock title %}

{% load static %}<!--cargo carpeta static '-->
{% block content %}
{% include 'include/header.html' %}
{% load rest_framework %}

    <form action="{% url 'luces_app:formulario2' %}" method = "POST" >

            {% csrf_token %}
            {% render_form serializer %}
            
        <input type="submit" value="Enviar">
    </form>

{% endblock content %}

templates/editar.html
{% extends 'include/base.html' %}

{% block title %}
Listado de luces

{% endblock title %}

{% load static %}<!--cargo carpeta static '-->
{% block content %}
{% include 'include/header.html' %}
{% load rest_framework %}
<div class="container">
    <div class="grid-container fluid">
        <div class="grid-x grid-margin-x">
            <div class = "cell small-6 large-4"></div>
            <div class = "cell small-6 large-4">
                <form action="{% url 'luces_app:editar' pk=luz.pk %}" method = "POST" >

                        {% csrf_token %}
                        {% render_form serializer %}
                        
                    <input type="submit" value="Enviar">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/include/base.html
{% load static %}<!--cargo carpeta static '-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
    <link rel="icon" href="img/logojs.png">
    <!--Ojo que la ruta en static va con '-->
    <title>

        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    {% block content %}
    {% endblock content %}

   <!--Cargo las librerias de javascript '-->

    <script src="{% static 'js/vendor/vendor.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}

<!-- <script>
    $(document).foundation();
    window.setTimeout(function () { window.location.reload(); }, 10000);
</script> -->




</body>


</html>

templates/include/header.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
  </div>
  
  <div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="has-submenu">
          <a href="{% url 'luces_app:Luces'%}">Lista de luces</a>
        </li>
        <li class="has-submenu">
          <a href="{% url 'luces_app:formulario2'%}">Agregar luces</a>
        </li>
      </ul>
    </div>
  </div>  

templates/include/javascript.html
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>


<script>

    //Puendo la luz
    function prendido(prendido) {
        let param = '?encendido='+ prendido;    
        send_request(param);
      }
    
    // Funcion para el cuadrito de busqueda.
    
    function buscar(){
        let id = document.getElementById('id').value;
        if (id === ''){
            id = '0';
        }
    
        id = '?id='+id;
        
        send_request(id);
    }
    
    //ejecuta prendido la primera vez que entras a la pagina, y por lo tanto me genera un listado con todas las luces.
    
    window.onload = function() {
        prendido("");
    };
    
    
    
    // Esta parte toma la solicitud GET y devuelve en funcion del parametro  param la informacion
    //la informacion es result y a su vez es dirigida a la funcion update_table(result)
    function send_request(param) {  
        var a = "{% url 'luces_app:prueba_list2'%}"
        $.ajax({
            method: 'GET',
            url: a + param,
            beforeSend: function() {
            },
            success: function(result) {
                update_table(result);
            },
            error: function(){
            }
        });
    }
    
    
    
    function send_update(param,estado) {  
        //aca obtengo las cookies segun la documentacion. 
        function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
            return cookieValue;
        }
    
        const csrftoken = getCookie('csrftoken');
        console.log(csrftoken)
    
    
        // aca armo la url con un valor pk 123, despues creo una nueva variable donde reemplazo 123
        // con el valor param
        var a = "{% url 'luces_app:update_prueba' 123 %}"
        var b = a.replace('123', param);
        console.log(b);
        var data = {};
        data.Luz = param;
        data.encendido = estado; 
    
        console.log(data);
        $.ajax({
            method: 'PUT',
            url: b,
            headers: {'X-CSRFToken': csrftoken},
            data:data,
    
        });
        location.reload();                                                                 
    };


    //te redirecciona a la pagina indicada. 

    function editar(param){
        let url = new URL(window.location.href);
        var a = url.origin + '/api/editar/' + param + "/"
        window.location.href = a;

    }



    function borrar(param){
         
        function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
            return cookieValue;
        }
    
        const csrftoken = getCookie('csrftoken');
        console.log(csrftoken);
    
    
        // aca armo la url con un valor pk 123, despues creo una nueva variable donde reemplazo 123
        // con el valor param
        var a = "{% url 'luces_app:delete_prueba' 123 %}"
        var b = a.replace('123', param);
        var mensaje = "Vas a borrar la siguiente luz: " + param
        var opcion = confirm(mensaje);
        if (opcion == true) {
                mensaje = confirm("Se borrara Luz" + param);
                $.ajax({
                    method: 'DELETE',
                    url: b,
                    headers: {'X-CSRFToken': csrftoken},
            
                });

        }else {
        mensaje = "Se ha cancelado el delete";
        alert(mensaje);
    }
        location.reload();   
    }
    
    //La funcion data toma automaticamente el resultado y va creando 
    //linea por lne los resultados. update_table(result) result es data. tema de nombres y resconstruye la tabla.
    
    function update_table(data) {
        let row;
        let all_rows = '';
    
        Object.keys(data).forEach(key => {
          elem = data[key];
          if (elem['encendido'] == true){
            row = '<tr> <td>' + elem['Luz'] + '</td>' + '<td>' + '<button  class="button alert" type="submit" onclick="send_update(' + elem['Luz'] + ',false)">' + 'Apagar Luz' + '</button>' + '</td>' + '<td>' + elem['Ip'] + '</td>' + '<td>' + elem['descripcion'] + '</td>'+ '<td>'+ '<button class="hollow button success" href="#" onClick="editar(' + elem['Luz'] + ');" type="button">' + '<i class="fas fa-align-center"></i>' + '</a>' + '</button>' +  '</td>'+ '</td>'+ '<button  class="button alert" type="submit" onclick="borrar(' + elem['Luz'] + ');"> borrar' + '<i class="fas fa-align-center"></i>' + '</a>' + '</button>'+  '</td>' + '<td>' + '<button  class="button alert" onclick="borrar('+ elem['Luz'] + ');">' +'<i class="fas fa-align-center"></i>' + '</a>' + '</button>' + '</td>' + '</tr>';
          }else if ((elem['encendido'] == false)){
            row = '<tr> <td>' + elem['Luz'] + '</td>' + '<td>' + '<button  class="success button" type="submit" onclick="send_update(' + elem['Luz'] + ',true)">' + 'Prender Luz' + '</button>' + '</td>' + '<td>' + elem['Ip'] + '</td>' + '<td>' + elem['descripcion'] + '</td>' + '<td>' + '<button class="hollow button success" href="#" onClick="editar(' + elem['Luz'] + ');" type="button">' + '<i class="fas fa-align-center"></i>' + '</a>' + '</button>'+ '</td>'+ '</td>'+ '<button  class="button alert" type="submit" onclick="borrar(' + elem['Luz'] + ');"> borrar' + '<i class="fas fa-align-center"></i>' + '</a>' + '</button>'+  '</td>' + '<td>' + '<button  class="button alert" onclick="borrar('+ elem['Luz'] + ');">' +'<i class="fas fa-align-center"></i>' + '</a>' + '</button>' + '</td>' + '</tr>';
          } 
          
          all_rows = all_rows + row;
        });
    
        $('#latabla tbody').html(all_rows);
      }
    
    </script>

templates/luces.html
{% extends 'include/base.html' %}

{% block title %}
Listado de luces
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock title %}

{% load static %}<!--cargo carpeta static '-->
{% block content %}
{% include 'include/header.html' %}
{% load rest_framework %}

{% csrf_token %}
<h1>en testeo</h1>
<ul>{% for x in luz %}
    <li>
        {% if x.encendido == True %}
         La luz {{x.Luz}} esta prendida
          <button  class="button alert" type="submit" onclick="{apagar({{x.Luz}})};">  <!-- pylint: disable=no-member -->
            Apagar Luz {{x.Luz}}
        </button>
        {% else %}
            La luz {{x.Luz}} esta apagada
            <button  class="success button" type="submit" onclick="{prender({{x.Luz}})};"> <!-- pylint: disable=no-member -->
                Encender Luz {{x.Luz}}
            </button>
        {% endif %}
        
        <a type="button" class="success button" href="{% url 'luces_app:editar' x.Luz %}">Editar Luz</a>
        <button  class="success button" type="submit" onclick="{borrar({{x.Luz}})};">borrar</button>

    </li>
    {% endfor %}

</ul>

<a type="button" class="success button" onclick= prueba()> Prueba</a>


<form action="http://192.168.1.5:8000/api/update/3/" method = "PUT" >

    {% csrf_token %}
    <input type="number" name="Luz" >
    {{ form.Luz }} 
    <input type="checkbox" name="encendido" value='false'>
    {{ form.encendido }}
    <input type="submit" value="Enviar">

</form>

<h1><a type="button" class="success button" href="/accounts/logout/">desloguearse</a></h1>    



<script>

function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');

function prueba() {
        console.log(csrftoken);
        var xhttp = new XMLHttpRequest();
        var ItemJSON;
        var data ;
        var URL;
        data = '{"Luz": 3,"encendido": true}'; 
        URL = 'http://192.168.1.5:8000/api/update/3/';
        xhttp.open("PUT",URL, true);
        xhttp.setRequestHeader("Content-type", "application/json","X-CSRFToken",csrftoken); 
        xhttp.send(data);
        // location.reload();
}


function prender(valor) {

    var xhttp = new XMLHttpRequest();
    var ItemJSON;
    var one = '{"Luz":';    
    var two = valor.toString();
    var three = ',"encendido": true}';
    ItemJSON = one + two + three;
    var URL;
    URL = 'http://192.168.1.5:8000/api/update/' + two + '/';
    xhttp.open("PUT",URL, true);
    xhttp.setRequestHeader("Content-type", "application/json"); 
    xhttp.send(ItemJSON);
    // location.reload();
}


function apagar(valor) {
    var xhttp = new XMLHttpRequest();
    var ItemJSON;
    var one = '{"Luz":';
    var two = valor.toString();
    var three = ',"encendido": false}';
    ItemJSON = one + two + three;

    var URL;
    URL = 'http://192.168.1.5:8000/api/update/' + two + '/';


    xhttp.open("PUT",URL, true);
    xhttp.setRequestHeader("Content-type", "application/json"); 
    xhttp.send(ItemJSON);
    // location.reload();
}

function borrar(valor) {
    var two = valor.toString();
    var mensaje = "Vas a borrar la siguiente luz: " + two;
    var opcion = confirm(mensaje);
    var xhttp = new XMLHttpRequest();
    var URL;
    
    URL = 'http://192.168.1.5:8000/api/delete/' + two + '/';

    if (opcion == true) {
        mensaje = confirm("Se borrara" + two);
        xhttp.open("DELETE",URL, true);
        xhttp.setRequestHeader("Content-type", "application/json");
        xhttp.send();
        mensaje = "Se borro" + two;
        alert(mensaje)
	}else {
        mensaje = "Se ha cancelado el delete";
        alert(mensaje);
    }
    location.reload();
}

</script>

{% endblock content %}

templates/luces2.html
{% extends 'include/base.html' %}

{% block title %}
Listado de luces
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock title %}

{% load static %}<!--cargo carpeta static '-->

{% block content %}
{% include 'include/header.html' %}
{% load rest_framework %}

{% csrf_token %}
<ul>{% for x in luz %}
    <li>
        {% if x.encendido == True %}
         La luz {{x.Luz}} esta prendida
          <button  class="button alert" type="submit" onclick="{apagar( {{x.Luz}} )};">  <!-- pylint: disable=no-member -->
            Apagar Luz {{x.Luz}}
        </button>
        {% else %}
            La luz {{x.Luz}} esta apagada
            <button  class="success button" type="submit" onclick="{prender( {{x.Luz}} )};"> <!-- pylint: disable=no-member -->
                Encender Luz {{x.Luz}}
            </button>
        {% endif %}
        
        <a type="button" class="success button" href="{% url 'luces_app:editar' x.Luz %}"> Editar Luz</a>
        <button  class="success button" type="submit" onclick="{borrar({{x.Luz}})};">borrar</button>

    </li>
    {% endfor %}

</ul>

<h1><a type="button" class="success button" href="/accounts/logout/">desloguearse</a></h1>    

<script>


function prender(valor) {
    var xhttp = new XMLHttpRequest();
    var ItemJSON;
    var one = '{"Luz":';    
    var two = valor.toString();
    var three = ',"encendido": true}';
    ItemJSON = one + two + three;
    var URL;
    URL = 'http://192.168.1.5:8000/api/update/' + two + '/';
    xhttp.open("PUT",URL, true);
    xhttp.setRequestHeader("Content-type", "application/json"); 
    xhttp.send(ItemJSON);
    // location.reload();
}


function apagar(valor) {
    var xhttp = new XMLHttpRequest();
    var ItemJSON;
    var one = '{"Luz":';
    var two = valor.toString();
    var three = ',"encendido": false}';
    ItemJSON = one + two + three;

    var URL;
    URL = 'http://192.168.1.5:8000/api/update/' + two + '/';


    xhttp.open("PUT",URL, true);
    xhttp.setRequestHeader("Content-type", "application/json"); 
    xhttp.send(ItemJSON);
    // location.reload();
}

function borrar(valor) {
    var two = valor.toString();
    var mensaje = "Vas a borrar la siguiente luz: " + two;
    var opcion = confirm(mensaje);
    var xhttp = new XMLHttpRequest();
    var URL;
    
    URL = 'http://192.168.1.5:8000/api/delete/' + two + '/';

    if (opcion == true) {
        mensaje = confirm("Se borrara" + two);
        xhttp.open("DELETE",URL, true);
        xhttp.setRequestHeader("Content-type", "application/json");
        xhttp.send();
        mensaje = "Se borro" + two;
        alert(mensaje)
	}else {
        mensaje = "Se ha cancelado el delete";
        alert(mensaje);
    }
    location.reload();
}

</script>

{% endblock content %}

templates/luces3.html
{% extends 'include/base.html' %}

{% block title %}

Listado de luces

{% endblock title %}

{% load static %}<!--cargo carpeta static '-->
{% block content %}
{% include 'include/header.html' %}
{% load rest_framework %}
<!--agrego los iconos.  '-->
<script defer src={% static 'js/all.min.js' %}></script>
<!--Titulo '-->
<div class="container">
    <div class="grid-container fluid">
        <div class="grid-x grid-margin-x">
            <div class = "cell small-6 large-4"></div>
            <div class = "cell small-6 ">
                <h3>Estado de luces con JS.<img src={% static 'img/logojs.png' %} width="30" height="40"></h3>
            </div>
        </div>
    </div>  
</div>

<!-- barra de busqueda y filtros. '-->
  <div class="container">
    <div class="grid-container fluid">
        <div class="grid-x grid-margin-x">
            <div class = "cell small-4 large-3"></div>
                <div class = "cell small-6 large-6">
                    <div class="input-group">
                        <div class="grid-x grid-padding-x">
                            <!-- onchage, llama a la funcion job_type que a su vez toma -->
                            <!-- el valor de this.value, valor que puede ser vacio, office o remote.  -->
                            <div class="cell small-4">
                                            <select onchange="prendido(this.value)">
                                                <option value="True">Encendido</option>
                                                <option value="False">Apagado</option>
                                                <option value="" selected="selected" >Todas</option>
                                            </select>
                            </div>
                            <div class="cell small-6">
                                            <form action="">
                                            <input type="text" id="id" size="10" placeholder="Id luz...">
                            </div>
                            <div class="cell small-2">
                                            <button class="hollow button success" onClick="buscar();" type="button">Search</button>
                                            </form>
                            </div>
                        </div>
                     </div>
                </div>
            </div>
        </div>
    </div>

<!-- tabla. '-->
    <div class="container">
        <div class="grid-container fluid">
            <div class="grid-x grid-margin-x">
                    <div class = "cell small-4 large-3"></div>
                        <div class = "cell small-6 large-6">
                                        <table class="stack" id="latabla">
                                        <thead>
                                            <!-- cabecera -->
                                            <tr>
                                            <th>Id</th>
                                            <th>Encendido</th>
                                            <th>Ip</th>
                                            <th>descripcion</th>
                                            <th>editar</th>
                                            <th>borrar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <!-- Aca automaticamente la funcion update table va a agrega las rows -->
                                        </tbody>

                                        </table>
                        </div>
                </div>
            
        </div>
    </div>
<!-- Boton de deslogueo. '-->
<div class="container">
    <div class="grid-container full">
    <div class="grid-x grid-margin-x">
        <div class = "cell small-4 large-4"></div>
            <div class = "cell small-6 large-4">
                <h1><a type="button" class="hollow button alert" href="/accounts/logout/">desloguearse</a></h1>
            </div>
        </div>
    </div>
    </div>    
</div>



{% endblock content %}

{% block javascript %}
{% include 'include/javascript.html' %}
{% endblock javascript %}

templates/panel.html
{% extends 'include/base.html' %}

{% block title %}
Panel de estado del Server  

{% endblock title %}

{% load static %}<!--cargo carpeta static '-->
{% block content %}
{% include 'include/header.html' %}
{% load rest_framework %}

{% csrf_token %}
<h1>Panel de estado del Server  </h1>

<p>{{name}}</p>
<p>carga de la cpu ultimos 15 minutos: {{cpu.load15}}</p>
<p>carga de la cpu ultimos 60 minutos: {{cpu.load60}}</p>
<p>Frecuencia de la CPU: {{cpu.freq}}</p>
<p>% de uso de ram: {{cpu.ram}}</p>

{% endblock content %}